"""Fix size embeddings vector

Revision ID: 459463ce7ce2
Revises: 6862993dee13
Create Date: 2026-02-02 22:27:03.518638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '459463ce7ce2'
down_revision: Union[str, Sequence[str], None] = '6862993dee13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embeddings',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embeddings',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
